### ISSUE TITLE
feat: Setup Dependabot for dependency updates

### ISSUE THREAD

**Issue by FidelusAleksander** [FidelusAleksander/prompt-action#1]
Set up Dependabot to automatically monitor and update dependencies:

1. Create `.github/dependabot.yml` with the following configuration:
```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
```

This will:
- Monitor npm dependencies weekly
- Create PRs for updates
- Label them appropriately
- Use conventional commit format

Benefits:
- Keeps dependencies up to date
- Reduces security vulnerabilities
- Automated maintenance
