### ISSUE TITLE
Add support for prompt-file parameter

### ISSUE THREAD

**Issue by FidelusAleksander** [FidelusAleksander/prompt-action#4]
Add support for `prompt-file` parameter to allow loading prompts from a file.

This would enable users to:
- Keep long prompts in separate files
- Version control their prompts
- Reuse prompts across different workflows

Example usage:
```yaml
- uses: FidelusAleksander/ask-ai@main
  with:
    prompt-file: .github/prompts/my-prompt.txt
```
