### ISSUE TITLE
Add support for GitHub Models prompt files

### ISSUE THREAD

**Issue by FidelusAleksander** [FidelusAleksander/prompt-action#58]
Add support for GitHub Models [.prompt.yml](https://docs.github.com/en/github-models/use-github-models/storing-prompts-in-github-repositories#supported-file-format) files

I'm imagining the interface could be like:

```yml
steps:
  - name: Prompt
    id: prompt
    uses: FidelusAleksander/prompt-action@v1
    with:
      prompt-file: './.github/prompts/sample.prompt.yml'
      input: |
         var1: hello
         var2: ${{ steps.<some-step>.outputs.<output> }}
         var3: |
           Lorem Ipsum
           Hello World

```
